name: 'Gradle Version Plugin Checker'
description: 'Use gradle version plugin to check if there are updates to your dependencies'
author: 'WtfJoke'
inputs:
  working_directory: 
    description: 'working directory where to execute gradle task dependencyUpdates'
outputs:
  has_updates:
    description: 'has updates to existing dependencies'
  update_text:
    description: 'Dependencies update information (existing and new version)'
  update_json:
    description: 'Dependencies update information (existing and new version) as json'
runs:
    using: node12
    main: dist/index.js
