name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
      - 'sampleProject2'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: |
        chmod +x demo/gradlew
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: |
        chmod +x demo/gradlew
    - uses: ./
      id: versionsaction
      with: 
        working_directory: demo
    - name: Check action output
      run: |
        echo has_update: "${{ steps.versionsaction.outputs.has_updates }}"